behaviors:
  MoveToFinishLine:
    trainer_type: ppo

    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear

    checkpoint_interval: 500000

    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

      gail:
        gamma: 0.99
        strength: 0.5
        demo_path: frontend_unity/Demos/MoveToFinishLine.demo

    max_steps: 2000000
    time_horizon: 64
    summary_freq: 50000

    behavioral_cloning:
      demo_path: frontend_unity/Demos/MoveToFinishLine.demo
      strength: 0.5
      steps: 500000
